// conf
export const SET_LANG = 'SET_LANG';

//app
export const START_LOADING = 'START_LOADING';
export const FINISHED_LOADING = 'FINISHED_LOADING';

// auth
export const SET_AUTH_USER = 'SET_AUTH_USER';
export const UNSET_AUTH_USER = 'UNSET_AUTH_USER';
export const UPDATE_USER_PASS = 'UPDATE_USER_PASS';


//login
export const CLEAR_LOGIN_ERRORS = 'CLEAR_LOGIN_ERRORS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

//reset
export const CLEAR_RESET_ERRORS = 'CLEAR_RESET_ERRORS';
export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_FAILURE = 'RESET_FAILURE';
export const RESET_SAVE_EMAIL = 'RESET_SAVE_EMAIL';

//registration
export const CLEAR_REGISTRATION_ERRORS = 'CLEAR_REGISTRATION_ERRORS';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';
export const UPLOAD_PICTURE_FAILURE = 'UPLOAD_PICTURE_FAILURE';

// notification
export const SHOW_SUCCESS_NOTIFICATION = 'SHOW_SUCCESS_NOTIFICATION';
export const HIDE_SUCCESS_NOTIFICATION = 'HIDE_SUCCESS_NOTIFICATION';
export const SHOW_WARNING_NOTIFICATION = 'SHOW_WARNING_NOTIFICATION';
export const HIDE_WARNING_NOTIFICATION = 'HIDE_WARNING_NOTIFICATION';
export const SHOW_ERROR_NOTIFICATION = 'SHOW_ERROR_NOTIFICATION';
export const HIDE_ERROR_NOTIFICATION = 'HIDE_ERROR_NOTIFICATION';
export const SHOW_INFO_NOTIFICATION = 'SHOW_INFO_NOTIFICATION';
export const HIDE_INFO_NOTIFICATION = 'HIDE_INFO_NOTIFICATION';
export const HIDE_ALL_NOTIFICATION = 'HIDE_ALL_NOTIFICATION';

// edit profile
export const REMOVE_CONTACT = 'REMOVE_CONTACT';
export const ADD_CONTACT = 'ADD_CONTACT';

export const CLEAR_EDIT_PROFILE_ERRORS = 'CLEAR_EDIT_PROFILE_ERRORS';
export const UPDATE_AUTH_USER_NAME = 'UPDATE_AUTH_USER_NAME';
export const UPDATE_AUTH_USER_EMAIL = 'UPDATE_AUTH_USER_EMAIL';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

// edit password
export const CLEAR_EDIT_PASSWORD_ERRORS = 'CLEAR_EDIT_PASSWORD_ERRORS';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILURE = 'UPDATE_PASSWORD_FAILURE';

// search
export const SEARCH_READY = 'SEARCH_READY';
export const SET_QUERY = 'SET_QWERY';
export const CLEAR_QWERY = 'CLEAR_QWERY';
export const SET_CONTACTS_SEARCH = 'SET_CONTACTS';
export const SET_DIALOGS_SEARCH = 'SET_DIALOGS_SEARCH';
export const SET_GLOBAL = 'SET_GLOBAL';
export const SET_FOUND = 'SET_FOUND';
export const CLEAR_FOUND = 'CLEAR_FOUND';

// dialogs
export const SET_DIALOGS = 'SET_DIALOGS';

// messages
export const SET_DIALOG_MESSAGES = 'SET_DIALOG_MESSAGES';
export const SET_CURRENT_DIALOG = 'SET_CURRENT_DIALOG';